export const MODEL_NAMES = {
  Tenant: 'Tenant',
  Location: 'Location',
  User: 'User',
  TenantMembership: 'TenantMembership',
  Customer: 'Customer',
  Service: 'Service',
  Staff: 'Staff',
  StaffService: 'StaffService',
  Schedule: 'Schedule',
  AvailabilityException: 'AvailabilityException',
  Appointment: 'Appointment',
  AppointmentIntervalLock: 'AppointmentIntervalLock',
  Channel: 'Channel',
  Conversation: 'Conversation',
  ConversationStateHistory: 'ConversationStateHistory',
  Message: 'Message',
  ProviderEvent: 'ProviderEvent',
  Notification: 'Notification',
  AuditEvent: 'AuditEvent',
} as const;

export const INDEX_NAMES = {
  tenantSlug: 'tenant_slug_unique',
  locationOrdering: 'location_ordering',
  userEmail: 'user_email_lowercase_unique',
  userPhone: 'user_phone_e164_unique',
  tenantMembership: 'tenant_membership_unique',
  tenantMembershipUser: 'tenant_membership_user_lookup',
  customerPhone: 'customer_phone_unique',
  customerOrdering: 'customer_ordering',
  serviceName: 'service_name_unique',
  servicePublic: 'service_public_lookup',
  staffLocation: 'staff_location_lookup',
  staffService: 'staff_service_unique',
  staffServiceEligibility: 'staff_service_eligibility_lookup',
  schedule: 'schedule_unique',
  scheduleLookup: 'schedule_lookup',
  availabilityException: 'availability_exception_lookup',
  appointmentIdempotency: 'appointment_idempotency_unique',
  appointmentAgenda: 'appointment_agenda_lookup',
  appointmentCustomer: 'appointment_customer_lookup',
  appointmentIntervalLock: 'appointment_interval_lock_unique',
  appointmentLockOwner: 'appointment_interval_lock_owner',
  channelExternalIdentity: 'channel_external_identity_unique',
  conversationExternalIdentity: 'conversation_external_identity_unique',
  conversationCustomer: 'conversation_customer_lookup',
  conversationHistory: 'conversation_history_ordering',
  messageConversation: 'message_conversation_ordering',
  messageProviderId: 'message_provider_id_unique',
  providerEventIdempotency: 'provider_event_idempotency_unique',
  notificationIdempotency: 'notification_idempotency_unique',
  notificationWorker: 'notification_worker_lookup',
  auditOrdering: 'audit_event_ordering',
} as const;
